services:
  influxdb:
    build:
      dockerfile: Dockerfile.influxdb
      args:
        A_INFLUXDB_HTTP_AUTH_ENABLED: ${INFLUXDB_HTTP_AUTH_ENABLED}
        A_INFLUXDB_DB: ${INFLUXDB_DB}
        A_INFLUXDB_USER: ${INFLUXDB_USER}
        A_INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
        A_INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
        A_INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
    ports:
      - "8086:8086"
    volumes:
      - ./myInfluxVolume:/var/lib/influxdb2
    env_file:
      - ./.env  
  geth:
    build:
      dockerfile: Dockerfile.geth
      args:        
        A_INFLUXDB_DB: ${INFLUXDB_DB}
        A_INFLUXDB_USER: ${INFLUXDB_USER}
    ports:
      - 30303:30303
      - 8551:8551
    volumes:
      - ./jwt:/tmp/
    env_file:
      - ./.env
    command: geth --metrics --metrics.influxdb --metrics.influxdb.endpoint "http://influxdb:8086" --metrics.influxdb.username '${INFLUXDB_USER}' --metrics.influxdb.password '${INFLUXDB_USER_PASSWORD}' --http.addr 0.0.0.0 --http --http.api eth,net,engine,admin --authrpc.addr geth --authrpc.port 8551 --authrpc.vhosts localhost,host.docker.internal --authrpc.jwtsecret /tmp/jwt.hex
  grafana:
    build:
      dockerfile: Dockerfile.geth
    ports:
      - 3000:3000
  beacon-node:
    build:
      dockerfile: Dockerfile.prysm    
    depends_on:
      - geth
    command: --accept-terms-of-use --datadir=/data --jwt-secret=/tmp/jwt.hex --rpc-host=0.0.0.0 --grpc-gateway-host=0.0.0.0 --monitoring-host=0.0.0.0 --execution-endpoint=http://geth:8551
    ports:
      - 4000:4000
      - 13000:13000
      - 12000:12000/udp
    volumes:
      - ./jwt:/tmp/
      - ./data:/data/
